### ISSUE TITLE
Instantiation of certificate profile failed

### ISSUE THREAD

**Issue by plusiv** [nordic-institute/X-Road-Security-Server-sidecar#92]
Got the error showed down below while trying to configure The X-Road Security Server Sidecar on a Kubernetes Cluster after deploy.

![Instantiation of certificate profile failed ID: fb295f849684b02a](https://user-images.githubusercontent.com/37001774/220003498-51c26e3a-f4c1-4ece-9147-c2e1220eb9d9.png)

The error occurred while I was creating the authentication keys.

I'm using the following set-up:
- Deployment mode: [Multiple Pods using a Load Balancer deployment](https://github.com/nordic-institute/X-Road-Security-Server-sidecar/blob/master/doc/kubernetes_security_server_sidecar_user_guide.md#456-multiple-pods-using-a-load-balancer-deployment)
- Images: `niis/xroad-security-server-sidecar:6.25.0-primary` and `niis/xroad-security-server-sidecar:6.25.0-secondary`
- Postgress Version: 12 (external database)
- Kubernetes Version: `v1.24.9`

I've tried looking for the error with the error code but no luck with that. Please, help.

**Comment by petkivim** [comment]
First, the X-Road version 6.25 isn't officially supported anymore. Currently, the officially supported versions are 7.0, 7.1 and 7.2. It's strongly recommended to use the latest available version. In your case it would mean using the `niis/xroad-security-server-sidecar:7.2.1-primary` and `niis/xroad-security-server-sidecar:7.2.1-secondary` images. However, the problem isn't caused by the non-supported image.

Could you connect to the container and check from the `/etc/xroad/globalconf/DO/shared-params.xml` configuration file the value of the `certificateProfileInfo` element of the CA that you’re using? The `approvedCA` section looks like this:

```xml
<approvedCA>
    <name>Xroad Test CA CN</name>
    <topCA>
        <cert>...</cert>
        <ocsp>
            <url>http://x.x.x.x/</url>
            <cert>MIIF...</cert>
        </ocsp>
    </topCA>
    <certificateProfileInfo>ee.ria.xroad.common.certificateprofile.impl.FiVRKCertificateProfileInfoProvider</certificateProfileInfo>
</approvedCA>
```

The most likely reason for the problem is that there's a wrong certificate profile info provider configured on the Central Server.

Also, you could check the `proxy_ui_api` log for details.

**Comment by plusiv** [comment]
Sure, the value of `certificateProfileInfo` is `ee.ria.xroad.common.certificateprofile.impl.OPTICCertificateProfileInfoProvider`.

**Comment by petkivim** [comment]
Instructions to submit a contribution are available [here](https://github.com/nordic-institute/X-Road/blob/develop/CONTRIBUTING.md).

**Comment by plusiv** [comment]
Thank you @petkivim for your help, I'm goin to follow your recommendations.
